version: '3.8'

services:
  fermibottle:
    # image: fssc/fermibottle:latest
    image: fermihips:25.05.15.1.amd64
    container_name: fermihips_container
    # user: fermi
    volumes:
      - /Volumes/MyHD/FERMI/input/newdata:/fermihips/newdata
      - /Volumes/MyHD/FERMI/output/hips:/fermihips/hips
      - /Volumes/MyHD/FERMI/output/working:/fermihips/working
      - /Volumes/MyHD/FERMI/output/last_week.txt:/fermihips/last_week.txt
    stdin_open: true
    tty: true
